### ISSUE TITLE
Painted Static Mesh error on play

### ISSUE THREAD

**Issue by ArieLeo** [slipster216/VertexPaint#10]
I'm getting error when going into play mode with painted static meshes.
Mesh are static and lightmapped, tested with 2 layer splat shaders, vertex color painted, uv flow painted.
Using refractivewater sample material. 
The flow are broken when going into play mode, 
Lightmap UV also sometimes broken (could it be related with UV2 are used as flowdir uv?)
also spammed with this error msg below.

`Not allowed to access vertices on mesh 'Combined Mesh (root: scene)'
UnityEngine.Mesh:get_vertices()
JBooth.VertexPainterPro.VertexInstanceStream:Apply(Boolean) (at Assets/Painter/VertexInstanceStream.cs:371)
JBooth.VertexPainterPro.VertexInstanceStream:Start() (at Assets/Painter/VertexInstanceStream.cs:104)
`
`Not allowed to access triangles/indices on mesh 'Combined Mesh (root: scene)'
UnityEngine.Mesh:get_triangles()
JBooth.VertexPainterPro.VertexInstanceStream:Apply(Boolean) (at Assets/Painter/VertexInstanceStream.cs:376)
JBooth.VertexPainterPro.VertexInstanceStream:Start() (at Assets/Painter/VertexInstanceStream.cs:104)
`
`Not allowed to access colors on mesh 'Combined Mesh (root: scene)'
UnityEngine.Mesh:get_colors()
JBooth.VertexPainterPro.VertexInstanceStream:EnforceOriginalMeshHasColors(Mesh) (at Assets/Painter/VertexInstanceStream.cs:124)
JBooth.VertexPainterPro.VertexInstanceStream:Apply(Boolean) (at Assets/Painter/VertexInstanceStream.cs:397)
JBooth.VertexPainterPro.VertexInstanceStream:Start() (at Assets/Painter/VertexInstanceStream.cs:104)
`

**Comment by slipster216** [comment]
You can't make the meshes static because then the mesh data won't be available on the CPU. If you want them static, you need to save them out as unique assets with the tools under the bake menu.

**Comment by ArieLeo** [comment]
Here's a sample of broken lightmap UV due it also use for FlowDirection
![lightmapuv](https://cloud.githubusercontent.com/assets/6450517/14761646/f0441b70-0999-11e6-8f5e-be85472fdf9c.png)

**Comment by ArieLeo** [comment]
woops you're commenting while i'm uploading :p 
i see, alright then.

**Comment by slipster216** [comment]
I use the third uv channel for flow, leaving the second for light mapping, so it should be ok. Perhaps you accidentally overwrote them by painting into the wrong channel? If so, you can remove that data and the originals will be used by clicking on that stream in the UI.

**Comment by ArieLeo** [comment]
just an information after the last pull, the lightmap uv problem are gone, it seems that related with the last shader fix.
Scratch that, the lightmap problem is stil there. even with 3 layer.
And i'm already painting on UV2 for flow map but it seems it's also use by lightmaps

**Comment by ArieLeo** [comment]
Ah i see. . . the lightmap problem occured if you using directional/Directional Specular Mode.
So UV2 are used by directional map??? :/

**Comment by ArieLeo** [comment]
the lightmap UV are fixed when removing the vertex instance stream manually then repaint.
