### ISSUE TITLE
[Unity 5.4] Brush Cursor Position Error

### ISSUE THREAD

**Issue by j1jeong** [slipster216/VertexPaint#13]
VertexPainterWindow_Painting.cs

```
>>>>>>>>>>>>>>> 2076
			float mult = 2;
			if (Application.unityVersion.StartsWith("5.3") )
			{
				mult = 1;
			}
===============
#if UNITY_5_3_OR_NEWER
			float mult = 1;
#else
			float mult = 2;
#endif
<<<<<<<<<<<<<<<
```

**Comment by slipster216** [comment]
This would actually inverse the change as UNITY_5_3_OR_NEWER would be defined on 5.4 as well. Also, that define isn't available on older versions of 5.3, so would raise the minimum level. 

That said, I still don't understand why this change seems to be necessary, or if it's potentially causing an issue on other versions of 5.4- I'm not sure why Unity would suddenly require that mouse coordinates be doubled, seems rather strange.

**Comment by ArieLeo** [comment]
I'm also getting this issue, the Brush transform are not aligned with the cursor.

**Comment by slipster216** [comment]
Yeah, on my unity version I have to double the mouse position- I'm not sure
why this started as it makes no sense. I'll check in an option for it in a
few hours so it can be toggled until I figure out if this is only on a
specific patch release or what..

**Comment by slipster216** [comment]
Are you on Windows or mac? I'm running on OS X and seem to need this offset on any version of 5.4. I know they added some type of 'Retna' thing to the OS X editor, so maybe that's why?

**Comment by slipster216** [comment]
Ok, I tried this on 5.4 as well as the latest patch release. On OSX, I still seem to need the multiply by 2 on the mouse coordinates. On Windows, however, it doesn't need this. So for now it only does this on OSX. I also put a support ticket in with Unity, so hopefully they'll get back to me and have some idea of what is going on. I really loath the idea of making this a setting - it should just work.

**Comment by ArieLeo** [comment]
I'm on windows, this is interesting issues, isn't there a platform dependent check in unity?
UNITY_EDITOR_WIN
UNITY_EDITOR_OSX

**Comment by slipster216** [comment]
Yea, but after further investigation it doesn't seem to be platform
specific either; I'm not sure if this is just something happening on my
machine, or on others, as Unity support has not been able to repro the
issue on their OSX devices..

**Comment by slipster216** [comment]
This is fixed, seems unity decided to add a constant which is either 1 or 2 depending on what type of monitor you have, and you can multiply by it to get the correct mouse position. Why it just doesn't come that way is beyond me though..
