### ISSUE TITLE
The name 'mult' does not exist in current context

### ISSUE THREAD

**Issue by ghost** [slipster216/VertexPaint#15]
After dragging files into the project asset folder, error shows up: 
"Assets/Editor/VertexPainterWindow_Painting.cs(2083,77): error CS0103: The name `mult' does not exist in the current context"
Tested on 5.4.1f1 and 5.3.1f1 versions of Unity Editor.
Tested Vertex Painter package has been downloaded at 10am(LA), November 5, 2016.

![ashampoo_snap_2016 11 05_20h43m03s_004_](https://cloud.githubusercontent.com/assets/23281304/20032314/f0ea1ba8-a398-11e6-98ac-809506edbd27.png)

Just tested on 5.3.2f1. Same thing! Am I doing something wrong...?((

**Comment by ghost** [comment]
Just got this. You must have been sleepy when was editing it last time :).

This chunk (2068):

```
         //float mult = 1;

         // WTF, for some reason, in Unity 5.4.1p3 I need to multiply the mouse coordinated by 2
         // for them to line up. 
         // 
         // Only seems to happen in OSX
         #if UNITY_EDITOR_OSX
         float mult = 2;
         if (Application.unityVersion.StartsWith("5.3"))
         {
            mult = 1;
         }
         #endif
```

Should be replaced with:

```
         float mult = 1;

         // WTF, for some reason, in Unity 5.4.1p3 I need to multiply the mouse coordinated by 2
         // for them to line up. 
         // 
         // Only seems to happen in OSX
         #if UNITY_EDITOR_OSX
         mult = 2;
         if (Application.unityVersion.StartsWith("5.3"))
         {
            mult = 1;
         }
         #endif
```

**Comment by slipster216** [comment]
been burning the candle at both ends.. Strangely, I had this flip back to
not being required on my machine the other day, then flip to being required
again. I put in a unity support ticket, but am thinking I'm just going to
make it an option for now (yuck).

**Comment by slipster216** [comment]
So I finally figured this out. In 5.4, they added a magic value that, on certain monitors, will be 2 and others 1, and you have to multiply your incoming mouse position by this value to get the correct mouse position. Seems obnoxious to me, like it should just give me a workable value instead.
