### ISSUE TITLE
Examples cause import to hang

### ISSUE THREAD

**Issue by Siccity** [slipster216/VertexPaint#27]
Great asset! I am submoduling it into my own game's repository so I can fetch updates with ease. But it hangs at a certain shader.
![image](https://user-images.githubusercontent.com/6402525/45562942-2013e480-b84c-11e8-8e4b-94fe71fe7592.png)
I'm on Unity 2017.1.0f3. 

Edit: While the examples are great, I would be interested in an alternative branch without them included. Just to keep a clean project. For now I'm gonna go with the manual approach downloading and extracting the .zip inside my project

**Comment by slipster216** [comment]
It takes like 10 minutes to compile that shader.. You can remove the ones
you aren't going to use (specular workflow, etc) to speed things up..
