### ISSUE TITLE
Assets/VertexPaint-master/VertexInstanceStream.cs(457,33): error CS0103: The name `meshStream' does not exist in the current context

### ISSUE THREAD

**Issue by Russel1** [slipster216/VertexPaint#4]
"private Mesh meshStream;" must be outside of #if UNITY_EDITOR construct for iOS or Android Build:

// hack around unity bugs in the editor..
        private Mesh meshStream;
# if UNITY_EDITOR

```
    public Mesh GetModifierMesh() {
        return meshStream;
    }

    void Update() {
        if (!Application.isPlaying) {
            MeshRenderer r = GetComponent<MeshRenderer>();
            r.additionalVertexStreams = meshStream;
        }
    }
```
# endif

**Comment by slipster216** [comment]
If you sync this is fixed, but by fixing the incorrect use of meshStream outside of the #if. Saves memory for a pointer at runtime.

**Comment by apautrot** [comment]
By looking at the code on GitHub I would rather say that meshStream is wrongly used on lines

```
meshStream.UploadMeshData(markNoLongerReadable);
mr.additionalVertexStreams = meshStream;

Profiler.EndSample();

Profiler.EndSample();
return meshStream;
```

and that stream should be used instead :

```
stream.UploadMeshData(markNoLongerReadable);
mr.additionalVertexStreams = stream;

Profiler.EndSample();

Profiler.EndSample();
return stream;
```

Also note that Profiler.EndSample(); appears twice, is that intended ?

**Comment by slipster216** [comment]
I must have forgotten to sync after submitting my change list; Yes, all of
those should be stream. The second EndSample is correct though; I've added
comments to the code to mark which profiler block they are closing so it'll
be easier to parse. (And this time I hit sync after submit)
