### ISSUE TITLE
Shader Init & Scale transform on Paint

### ISSUE THREAD

**Issue by kaneleka** [slipster216/VertexPaint#6]
Negative transforms on the mesh breaks PaintMesh method.
Quick Hack: 
-- float scale = 1.0f / j.renderer.transform.lossyScale.x;
++  float scale = 1.0f / Mathf.Abs(j.renderer.transform.lossyScale.x);

Uninitialized variable errors in shader VertexPainterPro_Preview using latest beta of unity.
Added:  UNITY_INITIALIZE_OUTPUT(v2f, o); 
to vert function.

Awesome tool btw!

**Comment by slipster216** [comment]
fixed, thanks!
