### ISSUE TITLE
Broken FlowMap when painting in Mesh exported from 3dsmax

### ISSUE THREAD

**Issue by ArieLeo** [slipster216/VertexPaint#7]
When painting flow on mesh exported from 3dsmax the flow direction are broken.
is it related with tangent space? and 3dsmax axis are using Z-up.
is there a way to support this rather than rotate the object pivot manually?

**Comment by slipster216** [comment]
Can you send me a mesh that has the issue? I currently use the normal and tangent to orientate the flow direction, so if the tangent space is computed correctly it should just work- but perhaps there's something I'm not computing correctly.

**Comment by ArieLeo** [comment]
Sure, here it is [https://goo.gl/Naku7U](https://goo.gl/Naku7U) inside you can find two fbx mesh

**Comment by ArieLeo** [comment]
Also here you can see the arrow debug
Left is Z-Up, Right is Y-Up. you can see in ZMesh the arrow are incorrect
![flowdebug](https://cloud.githubusercontent.com/assets/6450517/14681466/c87be6d8-0753-11e6-92a0-63f6611ad926.png)

**Comment by slipster216** [comment]
Fixed, thanks!

**Comment by ArieLeo** [comment]
Hmm i'm still getting this with the latest version

**Comment by slipster216** [comment]
So, I just double checked this by loading up both your meshes and painting a circle on them, and it all seems to work fine. Am I missing something in your repro?

result:
https://gyazo.com/d6ced55b29099d9a7ec82fc3e533178c

**Comment by ArieLeo** [comment]
okay it seems working now, weird i guess i did something wrong when updating earlier.
Thanks :)
