### ISSUE TITLE
Deform Brush Argument Exception error with Z-Up Mesh

### ISSUE THREAD

**Issue by ArieLeo** [slipster216/VertexPaint#8]
Alright new one, right now it's the deform brush.
When i'm trying to paint using the deform brush on a mesh that using z as up axis i'm getting this error.
`ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds.
System.Array.CopyTo (System.Array array, Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/Array.cs:1830)
JBooth.VertexPainterPro.VertexPainterWindow.EndStroke () (at Assets/Painter/Editor/VertexPainterWindow_Painting.cs:1484)
JBooth.VertexPainterPro.VertexPainterWindow.OnSceneGUI (UnityEditor.SceneView sceneView) (at Assets/Painter/Editor/VertexPainterWindow_Painting.cs:1824)
UnityEditor.SceneView.CallOnSceneGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:2043)
UnityEditor.SceneView.HandleSelectionAndOnSceneGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:1383)
UnityEditor.SceneView.OnGUI () (at C:/buildslave/unity/build/Editor/Mono/SceneView/SceneView.cs:1220)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
`
and unity scene view are locked, i have to restart unity fix the scene view.

**Comment by ArieLeo** [comment]
Oh and can i request something?.
Is it possible to have the same brush display as in deform brush for Color and flow brushes, and display every vertex under the brush with dotCap handles?
Basically i'm looking to have the same vertex brush display as in UE4 since it really helpful to know which vertex currently affected by the brush.
something like [this ](https://docs.unrealengine.com/latest/images/Engine/UI/LevelEditor/Modes/MeshPaintMode/VertexColor/PaintingOnMeshes/PaintStroke_Green.jpg)

**Comment by slipster216** [comment]
I have not been able to reproduce this error- any other steps that lead to it?

**Comment by slipster216** [comment]
added "Show Brush Influence" option that draws caps under the brush area..

**Comment by ArieLeo** [comment]
hmm i'm still unsure, it's kinda random.
Also for some reason after last pull and totally overwrite all the editor scripts including the VertexInstanceStream except examples folder, the problem seems fixed.
I'll let you know if it's happened again, let's hope not :)
Thanks

**Comment by ArieLeo** [comment]
The error happened if we reset or remove the VertexInstanceStream component from the mesh
